local mod = RegisterMod("The Binding Of Isaac - Ascention", 1)

local Geburah = include("scripts.characters.geburah")
local StartingPocketActives = include("scripts.characters.starting_pocket_actives")
local EyeOfSun = include("scripts.characters.eye_of_sun")
local EyeOfOldGod = include("scripts.eye_of_old_god")
local GoldenBracelet = include("scripts.golden_bracelet")
local EmpressTiara = include("scripts.empress_tiara")
local GoldenEyeWeaponAdapter = include("scripts.golden_eye_weapon_adapter")
local GoldenEye = include("scripts.golden_eye")
local Arclight = include("scripts.arclight")
local FlamingRose = include("scripts.flaming_rose")
local MiniIsaacChargeVisuals = include("scripts.minisaac.charge_visuals")
local MiniIsaacCombat = include("scripts.minisaac.combat")
local MiniIsaacRouter = include("scripts.minisaac.incubus_router")
local MiniIsaacPursuit = include("scripts.minisaac.pursuit")
local MiniIsaacAggro = include("scripts.minisaac.aggro")
local GeburahMiniIsaacHealth = include("scripts.minisaac.geburah_health")
local MiniIsaacSplitTears = include("scripts.minisaac.split_tears")
local MiniIsaacNativeWeaponAdapter = include("scripts.minisaac.native_weapon_adapter")
local MiniIsaacSpiritSwordAdapter = include("scripts.minisaac.spirit_sword_adapter")
local MiniIsaacSplitLasers = include("scripts.minisaac.split_lasers")
local RevelationRework = include("scripts.revelation_rework_v2")

local GOLDEN_EYE = Isaac.GetItemIdByName("Golden Eye")
local GOLDEN_EYE_FAMILIAR = Isaac.GetEntityVariantByName("Golden Eye Familiar")
local ARCLIGHT = Isaac.GetItemIdByName("Arclight")
local ARCLIGHT_SWORD = Isaac.GetEntityVariantByName("Arclight Sword")
local EMPRESS_TIARA = Isaac.GetItemIdByName("Empress's Tiara")
local FLAMING_ROSE = Isaac.GetItemIdByName("Flaming Rose")
local EYE_OF_OLD_GOD = Isaac.GetItemIdByName("Eye of the Old God")
local GOLDEN_BRACELET = Isaac.GetItemIdByName("Golden Bracelet")

Geburah.Register(mod, EMPRESS_TIARA)
StartingPocketActives.Register(mod)
EmpressTiara.Register(mod, EMPRESS_TIARA)
GoldenEye.Register(mod, GOLDEN_EYE, GOLDEN_EYE_FAMILIAR, GoldenEyeWeaponAdapter)
Arclight.Register(mod, ARCLIGHT, ARCLIGHT_SWORD)
FlamingRose.Register(mod, FLAMING_ROSE)
EyeOfOldGod.Register(mod, EYE_OF_OLD_GOD, EyeOfSun)
GoldenBracelet.Register(mod, GOLDEN_BRACELET)
MiniIsaacChargeVisuals.Register(mod)
MiniIsaacCombat.Register(mod)
MiniIsaacRouter.Register(mod)
MiniIsaacPursuit.Register(mod)
MiniIsaacAggro.Register(mod)
GeburahMiniIsaacHealth.Register(mod)
MiniIsaacSplitTears.Register(mod, MiniIsaacSplitLasers)
MiniIsaacNativeWeaponAdapter.Register(mod)
MiniIsaacSpiritSwordAdapter.Register(mod)
MiniIsaacSplitLasers.Register(mod)
EyeOfSun.Register(mod)
RevelationRework.Register(mod)
