local mod = RegisterMod("The Binding Of Isaac - Ascention", 1)

local Geburah = include("scripts.characters.geburah")
local EyeOfSun = include("scripts.characters.eye_of_sun")
local EmpressTiara = include("scripts.empress_tiara")
local GoldenEyeWeaponAdapter = include("scripts.golden_eye_weapon_adapter")
local GoldenEye = include("scripts.golden_eye")
local Arclight = include("scripts.arclight")
local MiniIsaacChargeVisuals = include("scripts.minisaac.charge_visuals")
local MiniIsaacCombat = include("scripts.minisaac.combat")
local MiniIsaacRouter = include("scripts.minisaac.incubus_router")
local MiniIsaacPursuit = include("scripts.minisaac.pursuit")
local GeburahMiniIsaacHealth = include("scripts.minisaac.geburah_health")
local MiniIsaacSplitTears = include("scripts.minisaac.split_tears")
local MiniIsaacNativeWeaponAdapter = include("scripts.minisaac.native_weapon_adapter")
local MiniIsaacSplitLasers = include("scripts.minisaac.split_lasers")
local RevelationRework = include("scripts.revelation_rework_v2")

local GOLDEN_EYE = Isaac.GetItemIdByName("Golden Eye")
local GOLDEN_EYE_FAMILIAR = Isaac.GetEntityVariantByName("Golden Eye Familiar")
local ARCLIGHT = Isaac.GetItemIdByName("Arclight")
local ARCLIGHT_SWORD = Isaac.GetEntityVariantByName("Arclight Sword")
local EMPRESS_TIARA = Isaac.GetItemIdByName("Empress's Tiara")

Geburah.Register(mod, EMPRESS_TIARA)
EmpressTiara.Register(mod, EMPRESS_TIARA)
GoldenEye.Register(mod, GOLDEN_EYE, GOLDEN_EYE_FAMILIAR, GoldenEyeWeaponAdapter)
Arclight.Register(mod, ARCLIGHT, ARCLIGHT_SWORD)
MiniIsaacChargeVisuals.Register(mod)
MiniIsaacCombat.Register(mod)
MiniIsaacRouter.Register(mod)
MiniIsaacPursuit.Register(mod)
GeburahMiniIsaacHealth.Register(mod)
MiniIsaacSplitTears.Register(mod, MiniIsaacSplitLasers)
MiniIsaacNativeWeaponAdapter.Register(mod)
MiniIsaacSplitLasers.Register(mod)
EyeOfSun.Register(mod)
RevelationRework.Register(mod)
